[build]
  command = "pnpm netlify-build"
  publish = ".next"

  [build.environment]
    POSTGRES_PRISMA_URL = "${NETLIFY_DATABASE_URL}"
    POSTGRES_URL_NON_POOLING = "${NETLIFY_DATABASE_URL_UNPOOLED}"

[template]
  required-extensions = ["neon"]
